
spring:
  devtools:
    restart:
      exclude: static/**,public/**
      # Close Hot Deployment.
      enabled: true

  redis:
    database: 0 # Indicate which database on Redis you want to manipulate(??).
    port: 6379      # Redis port is default 6379
    host: localhost
    # Other
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
        shutdown-timeout: 100ms

logging:
  config: classpath:log4j2.xml   # Specify the configuration file location for log4j2.